### ISSUE TITLE
Unable to install on Apple Silicon Mac

### ISSUE THREAD

**Issue by drego85** [RfidResearchGroup/homebrew-proxmark3#41] opened 2024-03-13 15:26 UTC
Hi,
during installation through brew I get this error:

```
Last 15 lines from /Users/xxxxxx/Library/Logs/Homebrew/proxmark3/02.make:
      _Pm3PyRun_SimpleFileNoExit in cmdscript.o
      __wrap_delete_pm3 in pm3_pywrap.o
      __wrap_pm3_name_get in pm3_pywrap.o
      _pm3_swigregister in pm3_pywrap.o
      _pm3_swiginit in pm3_pywrap.o
      _SWIG_Python_NewPointerObj in pm3_pywrap.o
      _SWIG_Python_ConvertPtrAndOwn in pm3_pywrap.o
      ...
  "__Py_NotImplementedStruct", referenced from:
      _SwigPyObject_richcompare in pm3_pywrap.o
      _SwigPyObject_richcompare in pm3_pywrap.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [proxmark3] Error 1
make: *** [client/all] Error 2

If reporting this issue please do so at (not Homebrew/brew or Homebrew/homebrew-core):
  https://github.com/rfidresearchgroup/homebrew-proxmark3/issues
```

Thanks you for the support!

**Comment by B3rJmp** [comment] 2024-03-13 23:45
Having this same issue ^^ Any updates?

**Comment by gl40** [comment] 2024-03-19 18:27
me too ^^

**Comment by nadja75** [comment] 2024-03-22 16:48
Same problem for me too

**Comment by cyba3r** [comment] 2024-03-23 18:01
Same Problem with M2 MacBook Pro

**Comment by DisreputableCode** [comment] 2024-03-30 06:14
One workaround is to unlink python from homebrew, install proxmark3, then relink python;
`brew unlink python
brew install proxmark3
brew link python`

**Comment by Johnnybyzhang** [comment] 2024-04-08 15:53
> One workaround is to unlink python from homebrew, install proxmark3, then relink python; `brew unlink python && brew install proxmark3 && brew link python`

This solved my issue, you are a champ!

**Comment by aidenfoxivey** [comment] 2024-04-30 18:04
> One workaround is to unlink python from homebrew, install proxmark3, then relink python; `brew unlink python && brew install proxmark3 && brew link python`

How does this work? I'm assuming the issue is that Python on the Mac system is normally a native executable. Does this then run a non-native Python with Rosetta?

**Comment by iceman1001** [comment] 2024-12-16 09:18
closing

**Closed by iceman1001** 2024-12-16 09:18 UTC
